name: Deploy Now

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: |
          npm run build
          npx next export

      - name: Deploy to IONOS
        env:
          DEPLOYMENT_FOLDER: out
        run: echo "Deploying to IONOS"
